# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: 127.0.0.1:9090

# DNS 设置
dns:
  enable: true
  ipv6: false
  default-nameserver: [223.5.5.5, 119.29.29.29]
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    [
      "+.lan",
      "*",
      "+.local",
      "+.cmpassport.com",
      "id6.me",
      "open.e.189.cn",
      "mdn.open.wo.cn",
      "opencloud.wostore.cn",
      "auth.wosms.cn",
      "+.10099.com.cn",
    ]
  use-hosts: true
  nameserver:
    [
      223.5.5.5,
      119.29.29.29,
      "https://doh.pub/dns-query",
      "https://dns.alidns.com/dns-query",
    ]
  #nameserver: ['system']
  fallback: [8.8.8.8, 1.1.1.1]
  fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4] }
  nameserver-policy: { "+.baidu.com": "system" }

# Stash
url-rewrite:
  - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
  - ^https?:\/\/(www.)?(g|google)\.com\.hk https://www.google.com 302
  - ^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302
