# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: 127.0.0.1:9090


# DNS 设置
dns:
  # 以下填写的 DNS 服务器将用于解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  # 支持 UDP / TCP / DoT / DoH / DoQ 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将直接发送到服务器，不经过任何代理。
  # Stash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    # 不建议配置超过 2 个 DNS 服务器，会增加系统功耗
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - system # 使用 iOS 系统 DNS
    # - quic://dns.adguard.com:853
    # - doq://test.dns.nextdns.io:853
 
  # 跳过证书验证，解决部分兼容性问题 https://help.nextdns.io/t/g9hdkjz
  skip-cert-verify: true
 
  # DNS 查询跟随代理规则
  follow-rule: false


# Stash
url-rewrite:
  - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
  - ^https?:\/\/(www.)?(g|google)\.com\.hk https://www.google.com 302
  - ^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302
